PROGRAM DRAW_HISTOGRAM

EXTERNAL PICTURE HISTOGRAM (SINGLE DIM(), STRING DIM(), BYTE)

DECLARE SINGLE VALUES (7), &
	STRING LABELS (7)

DATA 2.7, 3.5, 5.4, 3.6, 6.2, 5.9, 7.3, 5.4
DATA JAN, FEB, MAR, APR, MAY, JUN, JUL, AUG

FOR I = 0 TO 7
    READ VALUES(I)
NEXT I

FOR I = 0 TO 7
    READ LABELS(I)
NEXT I

DRAW HISTOGRAM (VALUES(), LABELS(), 8)

SLEEP 5%
END PROGRAM
